### PR TITLE
autocomplete 2.0; drastically performance improvement

### PR DESCRIPTION
**Pull request by darky**
Previous first implementation had stupid linear algorithm and time complexity was `~O(2n)`.
IDE was very laggy on autocomplete.

But now, implementation changed to using search engine `lunr` and it feels blazing fast in IDE 🚀

### CODE REVIEW

**Comment by darky** [comment]
Also added note about VSCode syntax highlight extension

**Comment by xialvjun** [comment]
So many thanks for your enthusiastic participation in this project.
In fact, when `ts-sql-plugin` can check all the sql in code in a cli way, it has achieved my goal. So seeing you make it better and better, I feel shamed. 
I hope to arouse enthusiasm to make it better, but I cann't. Maybe one day I can do it, but not now.
So:
I've add you as a collaborator so you can just push to this repo.
And tell me you npm account, I'll add you as this package's maintainer.

Of course you are not alone. I'm not leaving it, I'll keep telling my opinion on it, or sometimes write some code. So don't feel depressed.

So will you be the collaborator?

**Comment by darky** [comment]
@xialvjun thanks you very much for acknowledgment! Glad to read it)
Yep, I agree to collaborate this project. My npm profile: https://www.npmjs.com/~darrrk
Big thanks to you for this awesome project!
We use **ts-sql-plugin** in our work and have interest to support it!)

**Comment by xialvjun** [comment]
Cheers!
image

**Pull request merged**
