### PR TITLE
Cost check

### PR DESCRIPTION
**Pull request by o175**
add functionality for limiting explain cost - **maxExplainCost: number** 
(https://github.com/xialvjun/ts-sql-plugin/issues/8)

add functionality for showing explain output under pointer - **showExplain: boolean**

### CODE REVIEW

**Comment by darky** [comment]
Great stuff!

**Comment by xialvjun** [comment]
Sorry for not processing this PR soon. The IT industry in China is full of 996, too busy, feel tired.

I've change the two new options to: `error_cost, warn_cost, info_cost, and cost_pattern`.
Add `cost_pattern` in case of you are not using postgres.

**Comment by darky** [comment]
Great, thanks! It's so hard with 996, it feat! 🚀

**Comment by o175** [comment]
Thx! 
I had 69 recently and got tired too

**Pull request merged**
